"""
Module contains user defined objects directly implemented to map to the Element
API.
"""
from __future__ import unicode_literals
from __future__ import absolute_import
from solidfire.common import model as data_model

AUTO_GENERATE_SECRET = "AUTO-GENERATE-CHAP-SECRET"


class CHAPSecret(data_model.DataObject):
    """
    A representation of the CHAP Secret

    :param secret: [required] A 12 - 16 character string.
    :type start: str

    """

    secret = data_model.property(
        "secret", str,
        array=False, optional=False,
        documentation="A 12 - 16 character string."
    )

    def __init__(self, **kwargs):
        data_model.DataObject.__init__(self, **kwargs)

    @staticmethod
    def auto_generate():
        """
        Used in 'AddAccount' and 'ModifyAccount' to cause a CHAP Secret to be
        auto generated by the cluster.
        """
        chap = CHAPSecret()
        chap.secret = AUTO_GENERATE_SECRET
        return chap

    @classmethod
    def custom_extract(cls, data):
        """
        Deserialize the property from json.

        :param data: the data to be converted.

        :return: the extracted data.
        """
        chap = CHAPSecret()
        chap.secret = data
        return chap

    def custom_to_json(self):
        """
        Custom json serialize logic
        :return:
        """
        if self.secret == AUTO_GENERATE_SECRET:
            return None
        else:
            return self.secret


class Weekday:
    """
    A better representation of the Weekday.
    """

    Sunday = ('Sunday', 0)
    Monday = ('Monday', 1)
    Tuesday = ('Tuesday', 2)
    Wednesday = ('Wednesday', 3)
    Thursday = ('Thursday', 4)
    Friday = ('Friday', 5)
    Saturday = ('Saturday', 6)

    all_weekdays = [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday,
                    Saturday]

    @staticmethod
    def from_id(weekday_id):
        for weekday in Weekday.all_weekdays:
            if weekday[1] == weekday_id:
                return weekday
        raise AttributeError

    @staticmethod
    def from_name(weekday_name):
        for weekday in Weekday.all_weekdays:
            if weekday[0] == weekday_name:
                return weekday
        raise AttributeError


class Frequency(data_model.DataObject):
    """
    User Defined object (does not correlate to API Object) which simplifies
    the construction of Snapshot Schedule objects.

     :param minutes: Number of minutes between snapshots or the minute at
     which the snapshot will occur in "Days of Week", or "Days of Month" mode.
     Valid values  0 - 59
     :type minutes: int

    :param hours: Number of hours between snapshots or hour at which the
    snapshot will occur in "Days of Week", or "Days of Month" mode.
    Valid values  0 - 24
    :type hours: int

    :param monthdays: The days of the month that a snapshot will be made.
    Valid values  1 - 31
    :type monthdays: int[]

    :param weekdays: Day of the week the snapshot is to be created.
    Required Values (if used)
    Day - 0 - 6 (Sunday - Saturday).
    :type weekdays: Weekday[]

    :param days: Time Interval days between snapshot.
    :type days: int[]
    """

    def __init__(self, **kwargs):
        data_model.DataObject.__init__(self, **kwargs)


class TimeIntervalFrequency(Frequency):
    minutes = data_model.property(
        "minutes", int,
        array=False, optional=False,
        documentation="Number of minutes between snapshots. "
                      "Valid values are: 0 - 59"
    )

    hours = data_model.property(
        "hours", int,
        array=False, optional=False,
        documentation="Number of hours between snapshots. "
                      "Valid values are: 0 - 24"
    )
    days = data_model.property(
        "days", int,
        array=False, optional=False,
        documentation="Number of days between snapshots."
    )


class DaysOfWeekFrequency(Frequency):
    minutes = data_model.property(
        "minutes", int,
        array=False, optional=False,
        documentation="Minute of hour the snapshot is to be created. "
                      "Valid values are: 0 - 59"
    )

    hours = data_model.property(
        "hours", int,
        array=False, optional=False,
        documentation="Hour of day the snapshot is to be created. "
                      "Valid values are: 0 - 24"
    )
    weekdays = data_model.property(
        "weekdays", Weekday,
        array=True, optional=False,
        documentation="Days of the week the snapshot is to be created. "
                      "Valid values are: "
                      "Weekday - 1 - 7 (Sunday - Saturday)."
    )

class DaysOfMonthFrequency(Frequency):
    minutes = data_model.property(
        "minutes", int,
        array=False, optional=False,
        documentation="Minute of hour the snapshot is to be created. "
                      "Valid values are: 0 - 59"
    )

    hours = data_model.property(
        "hours", int,
        array=False, optional=False,
        documentation="Hour of day the snapshot is to be created. "
                      "Valid values are: 0 - 24"
    )
    monthdays = data_model.property(
        "monthdays", int,
        array=True, optional=False,
        documentation="Days of the month the snapshot is to be created. "
                      "Valid values are: 1 - 31"
    )

